version: "2"

services:
  lol:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4000:4000"
    env_file: .env
    environment:
        HOST: "localhost"
        MIX_ENV: "dev"
        PORT: "4000"
        SECRET_KEY_BASE: "1234"
    volumes:
      - .:/opt/app

  test:
    build:
      context: .
    environment:
      MIX_ENV: "test"
    volumes:
      - .:/opt/app
